### ISSUE TITLE
Suggestion: Move dead_end_iterator out of tests

### ISSUE THREAD

**Issue by parnmatt** [joboccara/pipes#1]
Loved your C++Now talk on this subject.

I don't understand why `fluent::dead_end_iterator` is implemented (and tested) *only* in tests.
Why not move `tests/dead_end_iterator.hpp` to either the root directory, or `output`?

**Comment by joboccara** [comment]
Done. dead_end_iterator is now called dev_null and is located in the include/ directory along with the other components.
Thanks!
