### ISSUE TITLE
tests: missing Makefile (or equivalent)

### ISSUE THREAD

**Issue by rnsanchez** [joboccara/pipes#12]
It should greatly assist on testing the code with the inclusion of something like a Makefile for building the test cases.  Direct benefits include:

1. Making sure the code compiles correctly on supported platforms;
2. Making sure the code is functioning (i.e., test cases run as intended);
3. Catching regressions early on.

**Comment by claremacrae** [comment]
A CMake would be ideal for a fair number of users.

**Comment by rnsanchez** [comment]
Agreed; possibly easier to maintain across multiple platforms.

**Comment by joboccara** [comment]
Indeed! I've tried to add CMake support with this [fix](https://github.com/joboccara/pipes/commit/89ea7a8a5ee854115ce2a3c098e262d0b08cb713). Does it look OK to you?

**Comment by claremacrae** [comment]
Thanks Jonathan. 

I’m not by a computer to be able to test this, but it looks good. 

From memory, as a later step, it might be worth calling enable_testing enabling CTest  integration.

**Comment by rnsanchez** [comment]
It worked great; thanks!

(OK by me for closing this issue.)
