### ISSUE TITLE
tee example

### ISSUE THREAD

**Issue by Porsche9II** [joboccara/pipes#17]
something is missing in the tee description - probably a transform and filter statement:

auto const inputs = std::vector<int>{1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
auto intermediaryResults = std::vector<int>{};
auto results = std::vector<int>{};

inputs >>= pipes::tee(pipes::push_back(intermediaryResults))
       >>= pipes::push_back(results);

// intermediaryResults contains {2, 4, 6, 8, 10, 12, 14, 16, 18, 20}
// results contains {12, 14, 16, 18, 20}

**Comment by joboccara** [comment]
Since the proposed fix has been merged, I'll close this thread.
