### ISSUE TITLE
Some pipes (e.g. filter) can cause their input value to be moved more than once.

### ISSUE THREAD

**Issue by LouisCharlesC** [joboccara/pipes#18]
The onReceive member function of the filter pipe forwards their input value both to the predicate_ and to the tailPipeline. This can lead to the value being moved more than once if both take the argument by value or &&.
Some other pipes also forward their input value more than once.

See below for a test you can add to filter to detect the issue.

I think the fix for filter is to not forward to the predicate, as predicates are likely to take their arguments by const&.
For other pipes, you may want to think about where it is more likely that forwarding will serve.

```c++
class TwoMoveDetector
{
public:
	TwoMoveDetector() = default;
	TwoMoveDetector(const TwoMoveDetector& other) = default;
	TwoMoveDetector(TwoMoveDetector&& other)
	{
		REQUIRE_FALSE(other.m_movedFrom);
		other.m_movedFrom = true;
	}

private:
	bool m_movedFrom = false;
};

TEST_CASE("filter moves value at most once")
{
    std::vector<TwoMoveDetector> input(1);
    auto const passthrough = pipes::filter([](TwoMoveDetector){return true;});
        
    std::vector<TwoMoveDetector> results;
    std::copy(std::make_move_iterator(begin(input)), std::make_move_iterator(end(input)), passthrough >>= pipes::push_back(results));
}
```

**Comment by LouisCharlesC** [comment]
Here's a test that makes much more sense to me!

```c++
TEST_CASE("filter predicate and pipeline get the input value")
{
	const std::vector<std::vector<int>> original = {{1,2,3,4}, {5,6,7,8}};
	std::vector<std::vector<int>> input = original;

	std::vector<std::vector<int>> valueSeenByThePredicate;
	auto const copyPassthroughFilter = pipes::filter(
		[&valueSeenByThePredicate]
		(std::vector<int> value)
		{
			valueSeenByThePredicate.push_back(value);
			return true;
		});
				
	std::vector<std::vector<int>> results;
	std::copy(std::make_move_iterator(begin(input)), std::make_move_iterator(end(input)), copyPassthroughFilter >>= pipes::push_back(results));

	REQUIRE(std::equal(original.cbegin(), original.cend(), valueSeenByThePredicate.cbegin()));
	REQUIRE(std::equal(original.cbegin(), original.cend(), results.cbegin()));
}
```

**Comment by LouisCharlesC** [comment]
Oh, and then the precise issue is not double move, but simply use after move if the predicate moves the value. Whatever the rest of the pipeline does it will do it on moved from values!

And I did sound like you had a choice for the fix, but basically you can only forward at the last use of a variable.
The only flexibility you have is to reorder operations if you feel it is more beneficial to forward at one place rather than the other. Most of the time you don't even have the freedom to reorder, though.

**Comment by joboccara** [comment]
Thanks! I went for solution 1 because it seems to me more consistent with the STL.
The fix is in this commit: https://github.com/joboccara/pipes/commit/b79dcfbcafa890e2e4503d90531127023fd3f850
