### ISSUE TITLE
[review] possible bug

### ISSUE THREAD

**Issue by DaMilyutin** [joboccara/pipes#28]
in include/pipes/base.hpp there is 
    struct pipeline_base : detail::crtp<Derived, pipeline_base>
    {
...
        Derived& operator++() { return this->derived(); } // should here be ++this->derived();
...    };

**Comment by joboccara** [comment]
Thanks for bringing this up.
This is supposed to be intentional, as the derived class don't have an operator++. The point of having the base class have one is to make the code of STL algorithms compile, while all the work is done by the operator=.
