### ISSUE TITLE
Add CMake support

### ISSUE THREAD

**Issue by TartanLlama** [joboccara/pipes#3]
It would be good to have CMake support so that users can easily add the library to their projects, tests can be built and run, and Vcpkg/Conan can support it. Ideally one could install the library through CMake and then use it like:

```
find_package(pipes REQUIRED)
target_link_libraries(my_target PRIVATE joboccara::pipes)
```

**Comment by joboccara** [comment]
Indeed. I've tried to add CMake support with this [fix](https://github.com/joboccara/pipes/commit/89ea7a8a5ee854115ce2a3c098e262d0b08cb713). Does it look OK to you?

**Comment by TartanLlama** [comment]
Ideally it should also have install targets. This blog post has a good example: http://dominikberner.ch/cmake-interface-lib/

**Comment by joboccara** [comment]
Ok, nice blog post. I've added install instructions in this [new fix](https://github.com/joboccara/pipes/commit/3183941b490d02153390beea0cd7f41c35cc11b1).

**Comment by TartanLlama** [comment]
Looks like it's missing the Config file part of the blog post, which is needed for users to get automatic access to the target after finding the package

**Comment by joboccara** [comment]
Really not a CMake expert, but I think I did it with this [new fix](https://github.com/joboccara/pipes/commit/305652daf3a3d6e02225b0a6e47463b3a8753f47).

**Comment by ankitthakar** [comment]
I tried to install with provided CMake and it seems to work.
