### ISSUE TITLE
`optional` storage may be misaligned

### ISSUE THREAD

**Issue by TartanLlama** [joboccara/pipes#5]
The implementation of `optional` in `helpers` stores objects in a character buffer, but the buffer may not meet the alignment requirements for types stored in it.

**Comment by joboccara** [comment]
Thanks!
I've made a [fix](https://github.com/joboccara/pipes/commit/842cb9b4ca6c2711d1f38dd8dac768fefe8e5b47) for this. Does it look OK to you now?

**Comment by TartanLlama** [comment]
I'd get rid of the [1], but otherwise yeah!

**Comment by joboccara** [comment]
Ok thanks. For the record, I can't seem to get rid of it and still specify I'd like one T in my buffer: the code doesn't compile if I just remove [1]. Maybe it's because I'm not familiar with aligned_storage, but it's no big issue anyway.

**Comment by TartanLlama** [comment]
If you remove the `[1]` you'd also need to explicitly take the address of `m_object` when you `reinterpret_cast` or placement `new` into it.

**Comment by joboccara** [comment]
Oh, right. It's done now ([commit](https://github.com/joboccara/pipes/commit/b21e77f0dec30f061476b1ff5a4883c966555851)). Thanks a lot, I wasn't familiar with aligned_storage before.
