### ISSUE TITLE
Start marking releases

### ISSUE THREAD

**Issue by hnOsmium0001** [joboccara/pipes#51]
Currently there is no releases for this library (and I assume we are supposed to make a copy of this in our own projects?). It would nice if you can mark releases, this way it can be added to package managers such as Conan.

**Comment by joboccara** [comment]
I've just tagged a version. Is this what you had in mind?

**Comment by hnOsmium0001** [comment]
Yes that's what I meant originally, and thanks for that. Although some time after posting this issue I found a commit number do just fine, but forgot to close this issue.

It would more convinient if versions exist, but if that makes your life harder than just ignore this issue :)
